# src/config/tickers.py
# =====================
# Central mapping of NIFTY 500 Stocks to their respective Industries/Sectors.

TICKER_MAP = {
    "360ONE.NS": "Financial Services",
    "3MINDIA.NS": "Diversified",
    "ABB.NS": "Capital Goods",
    "ACC.NS": "Construction Materials",
    "AIAENG.NS": "Capital Goods",
    "APLAPOLLO.NS": "Capital Goods",
    "AUBANK.NS": "Financial Services",
    "AADHARHFC.NS": "Financial Services",
    "AARTIIND.NS": "Chemicals",
    "AAVAS.NS": "Financial Services",
    "ABBOTINDIA.NS": "Healthcare",
    "ACE.NS": "Capital Goods",
    "ADANIENSOL.NS": "Power",
    "ADANIENT.NS": "Metals & Mining",
    "ADANIGREEN.NS": "Power",
    "ADANIPORTS.NS": "Services",
    "ADANIPOWER.NS": "Power",
    "ATGL.NS": "Oil Gas & Consumable Fuels",
    "AWL.NS": "Fast Moving Consumer Goods",
    "ABCAPITAL.NS": "Financial Services",
    "ABFRL.NS": "Consumer Services",
    "ABREL.NS": "Forest Materials",
    "ABSLAMC.NS": "Financial Services",
    "AEGISLOG.NS": "Oil Gas & Consumable Fuels",
    "AFFLE.NS": "Information Technology",
    "AJANTPHARM.NS": "Healthcare",
    "AKUMS.NS": "Healthcare",
    "APLLTD.NS": "Healthcare",
    "ALKEM.NS": "Healthcare",
    "ALKYLAMINE.NS": "Chemicals",
    "ALOKINDS.NS": "Textiles",
    "ARE&M.NS": "Automobile and Auto Components",
    "AMBER.NS": "Consumer Durables",
    "AMBUJACEM.NS": "Construction Materials",
    "ANANDRATHI.NS": "Financial Services",
    "ANANTRAJ.NS": "Realty",
    "ANGELONE.NS": "Financial Services",
    "APARINDS.NS": "Capital Goods",
    "APOLLOHOSP.NS": "Healthcare",
    "APOLLOTYRE.NS": "Automobile and Auto Components",
    "APTUS.NS": "Financial Services",
    "ACI.NS": "Chemicals",
    "ASAHIINDIA.NS": "Automobile and Auto Components",
    "ASHOKLEY.NS": "Capital Goods",
    "ASIANPAINT.NS": "Consumer Durables",
    "ASTERDM.NS": "Healthcare",
    "ASTRAZEN.NS": "Healthcare",
    "ASTRAL.NS": "Capital Goods",
    "ATUL.NS": "Chemicals",
    "AUROPHARMA.NS": "Healthcare",
    "AVANTIFEED.NS": "Fast Moving Consumer Goods",
    "DMART.NS": "Consumer Services",
    "AXISBANK.NS": "Financial Services",
    "BASF.NS": "Chemicals",
    "BEML.NS": "Capital Goods",
    "BLS.NS": "Consumer Services",
    "BSE.NS": "Financial Services",
    "BAJAJ-AUTO.NS": "Automobile and Auto Components",
    "BAJFINANCE.NS": "Financial Services",
    "BAJAJFINSV.NS": "Financial Services",
    "BAJAJHLDNG.NS": "Financial Services",
    "BALAMINES.NS": "Chemicals",
    "BALKRISIND.NS": "Automobile and Auto Components",
    "BALRAMCHIN.NS": "Fast Moving Consumer Goods",
    "BANDHANBNK.NS": "Financial Services",
    "BANKBARODA.NS": "Financial Services",
    "BANKINDIA.NS": "Financial Services",
    "MAHABANK.NS": "Financial Services",
    "BATAINDIA.NS": "Consumer Durables",
    "BAYERCROP.NS": "Chemicals",
    "BERGEPAINT.NS": "Consumer Durables",
    "BDL.NS": "Capital Goods",
    "BEL.NS": "Capital Goods",
    "BHARATFORG.NS": "Automobile and Auto Components",
    "BHEL.NS": "Capital Goods",
    "BPCL.NS": "Oil Gas & Consumable Fuels",
    "BHARTIARTL.NS": "Telecommunication",
    "BHARTIHEXA.NS": "Telecommunication",
    "BIKAJI.NS": "Fast Moving Consumer Goods",
    "BIOCON.NS": "Healthcare",
    "BIRLACORPN.NS": "Construction Materials",
    "BSOFT.NS": "Information Technology",
    "BLUEDART.NS": "Services",
    "BLUESTARCO.NS": "Consumer Durables",
    "BBTC.NS": "Fast Moving Consumer Goods",
    "BOSCHLTD.NS": "Automobile and Auto Components",
    "BRIGADE.NS": "Realty",
    "BRITANNIA.NS": "Fast Moving Consumer Goods",
    "MAPMYINDIA.NS": "Information Technology",
    "CCL.NS": "Fast Moving Consumer Goods",
    "CESC.NS": "Power",
    "CGPOWER.NS": "Capital Goods",
    "CIEINDIA.NS": "Automobile and Auto Components",
    "CRISIL.NS": "Financial Services",
    "CAMPUS.NS": "Consumer Durables",
    "CANFINHOME.NS": "Financial Services",
    "CANBK.NS": "Financial Services",
    "CAPLIPOINT.NS": "Healthcare",
    "CGCL.NS": "Financial Services",
    "CARBORUNIV.NS": "Capital Goods",
    "CASTROLIND.NS": "Oil Gas & Consumable Fuels",
    "CEATLTD.NS": "Automobile and Auto Components",
    "CELLO.NS": "Consumer Durables",
    "CENTRALBK.NS": "Financial Services",
    "CDSL.NS": "Financial Services",
    "CENTURYPLY.NS": "Consumer Durables",
    "CERA.NS": "Consumer Durables",
    "CHALET.NS": "Consumer Services",
    "CHAMBLFERT.NS": "Chemicals",
    "CHEMPLASTS.NS": "Chemicals",
    "CHENNPETRO.NS": "Oil Gas & Consumable Fuels",
    "CHOLAHLDNG.NS": "Financial Services",
    "CHOLAFIN.NS": "Financial Services",
    "CIPLA.NS": "Healthcare",
    "CUB.NS": "Financial Services",
    "CLEAN.NS": "Chemicals",
    "COALINDIA.NS": "Oil Gas & Consumable Fuels",
    "COCHINSHIP.NS": "Capital Goods",
    "COFORGE.NS": "Information Technology",
    "COLPAL.NS": "Fast Moving Consumer Goods",
    "CAMS.NS": "Financial Services",
    "CONCORDBIO.NS": "Healthcare",
    "CONCOR.NS": "Services",
    "COROMANDEL.NS": "Chemicals",
    "CRAFTSMAN.NS": "Automobile and Auto Components",
    "CREDITACC.NS": "Financial Services",
    "CROMPTON.NS": "Consumer Durables",
    "CUMMINSIND.NS": "Capital Goods",
    "CYIENT.NS": "Information Technology",
    "DLF.NS": "Realty",
    "DOMS.NS": "Fast Moving Consumer Goods",
    "DABUR.NS": "Fast Moving Consumer Goods",
    "DALBHARAT.NS": "Construction Materials",
    "DATAPATTNS.NS": "Capital Goods",
    "DEEPAKFERT.NS": "Chemicals",
    "DEEPAKNTR.NS": "Chemicals",
    "DELHIVERY.NS": "Services",
    "DEVYANI.NS": "Consumer Services",
    "DIVISLAB.NS": "Healthcare",
    "DIXON.NS": "Consumer Durables",
    "LALPATHLAB.NS": "Healthcare",
    "DRREDDY.NS": "Healthcare",
    "EIDPARRY.NS": "Chemicals",
    "EIHOTEL.NS": "Consumer Services",
    "EASEMYTRIP.NS": "Consumer Services",
    "EICHERMOT.NS": "Automobile and Auto Components",
    "ELECON.NS": "Capital Goods",
    "ELGIEQUIP.NS": "Capital Goods",
    "EMAMILTD.NS": "Fast Moving Consumer Goods",
    "EMCURE.NS": "Healthcare",
    "ENDURANCE.NS": "Automobile and Auto Components",
    "ENGINERSIN.NS": "Construction",
    "EQUITASBNK.NS": "Financial Services",
    "ERIS.NS": "Healthcare",
    "ESCORTS.NS": "Capital Goods",
    "EXIDEIND.NS": "Automobile and Auto Components",
    "NYKAA.NS": "Consumer Services",
    "FEDERALBNK.NS": "Financial Services",
    "FACT.NS": "Chemicals",
    "FINEORG.NS": "Chemicals",
    "FINCABLES.NS": "Capital Goods",
    "FINPIPE.NS": "Capital Goods",
    "FSL.NS": "Services",
    "FIVESTAR.NS": "Financial Services",
    "FORTIS.NS": "Healthcare",
    "GRINFRA.NS": "Construction",
    "GAIL.NS": "Oil Gas & Consumable Fuels",
    "GVT&D.NS": "Capital Goods",
    "GMRINFRA.NS": "Services",
    "GRSE.NS": "Capital Goods",
    "GICRE.NS": "Financial Services",
    "GILLETTE.NS": "Fast Moving Consumer Goods",
    "GLAND.NS": "Healthcare",
    "GLAXO.NS": "Healthcare",
    "GLENMARK.NS": "Healthcare",
    "MEDANTA.NS": "Healthcare",
    "GODIGIT.NS": "Financial Services",
    "GPIL.NS": "Capital Goods",
    "GODFRYPHLP.NS": "Fast Moving Consumer Goods",
    "GODREJAGRO.NS": "Fast Moving Consumer Goods",
    "GODREJCP.NS": "Fast Moving Consumer Goods",
    "GODREJIND.NS": "Diversified",
    "GODREJPROP.NS": "Realty",
    "GRANULES.NS": "Healthcare",
    "GRAPHITE.NS": "Capital Goods",
    "GRASIM.NS": "Construction Materials",
    "GESHIP.NS": "Services",
    "GRINDWELL.NS": "Capital Goods",
    "GAEL.NS": "Fast Moving Consumer Goods",
    "FLUOROCHEM.NS": "Chemicals",
    "GUJGASLTD.NS": "Oil Gas & Consumable Fuels",
    "GMDCLTD.NS": "Metals & Mining",
    "GNFC.NS": "Chemicals",
    "GPPL.NS": "Services",
    "GSFC.NS": "Chemicals",
    "GSPL.NS": "Oil Gas & Consumable Fuels",
    "HEG.NS": "Capital Goods",
    "HBLPOWER.NS": "Automobile and Auto Components",
    "HCLTECH.NS": "Information Technology",
    "HDFCAMC.NS": "Financial Services",
    "HDFCBANK.NS": "Financial Services",
    "HDFCLIFE.NS": "Financial Services",
    "HFCL.NS": "Telecommunication",
    "HAPPSTMNDS.NS": "Information Technology",
    "HAVELLS.NS": "Consumer Durables",
    "HEROMOTOCO.NS": "Automobile and Auto Components",
    "HSCL.NS": "Chemicals",
    "HINDALCO.NS": "Metals & Mining",
    "HAL.NS": "Capital Goods",
    "HINDCOPPER.NS": "Metals & Mining",
    "HINDPETRO.NS": "Oil Gas & Consumable Fuels",
    "HINDUNILVR.NS": "Fast Moving Consumer Goods",
    "HINDZINC.NS": "Metals & Mining",
    "POWERINDIA.NS": "Capital Goods",
    "HOMEFIRST.NS": "Financial Services",
    "HONASA.NS": "Fast Moving Consumer Goods",
    "HONAUT.NS": "Capital Goods",
    "HUDCO.NS": "Financial Services",
    "ICICIBANK.NS": "Financial Services",
    "ICICIGI.NS": "Financial Services",
    "ICICIPRULI.NS": "Financial Services",
    "ISEC.NS": "Financial Services",
    "IDBI.NS": "Financial Services",
    "IDFCFIRSTB.NS": "Financial Services",
    "IFCI.NS": "Financial Services",
    "IIFL.NS": "Financial Services",
    "INOXINDIA.NS": "Capital Goods",
    "IRB.NS": "Construction",
    "IRCON.NS": "Construction",
    "ITC.NS": "Fast Moving Consumer Goods",
    "ITI.NS": "Telecommunication",
    "INDGN.NS": "Healthcare",
    "INDIACEM.NS": "Construction Materials",
    "INDIAMART.NS": "Consumer Services",
    "INDIANB.NS": "Financial Services",
    "IEX.NS": "Financial Services",
    "INDHOTEL.NS": "Consumer Services",
    "IOC.NS": "Oil Gas & Consumable Fuels",
    "IOB.NS": "Financial Services",
    "IRCTC.NS": "Consumer Services",
    "IRFC.NS": "Financial Services",
    "IREDA.NS": "Financial Services",
    "IGL.NS": "Oil Gas & Consumable Fuels",
    "INDUSTOWER.NS": "Telecommunication",
    "INDUSINDBK.NS": "Financial Services",
    "NAUKRI.NS": "Consumer Services",
    "INFY.NS": "Information Technology",
    "INOXWIND.NS": "Capital Goods",
    "INTELLECT.NS": "Information Technology",
    "INDIGO.NS": "Services",
    "IPCALAB.NS": "Healthcare",
    "JBCHEPHARM.NS": "Healthcare",
    "JKCEMENT.NS": "Construction Materials",
    "JBMA.NS": "Automobile and Auto Components",
    "JKLAKSHMI.NS": "Construction Materials",
    "JKTYRE.NS": "Automobile and Auto Components",
    "JMFINANCIL.NS": "Financial Services",
    "JSWENERGY.NS": "Power",
    "JSWINFRA.NS": "Services",
    "JSWSTEEL.NS": "Metals & Mining",
    "JPPOWER.NS": "Power",
    "J&KBANK.NS": "Financial Services",
    "JINDALSAW.NS": "Capital Goods",
    "JSL.NS": "Metals & Mining",
    "JINDALSTEL.NS": "Metals & Mining",
    "JIOFIN.NS": "Financial Services",
    "JUBLFOOD.NS": "Consumer Services",
    "JUBLINGREA.NS": "Chemicals",
    "JUBLPHARMA.NS": "Healthcare",
    "JWL.NS": "Capital Goods",
    "JUSTDIAL.NS": "Consumer Services",
    "JYOTHYLAB.NS": "Fast Moving Consumer Goods",
    "JYOTICNC.NS": "Capital Goods",
    "KPRMILL.NS": "Textiles",
    "KEI.NS": "Capital Goods",
    "KNRCON.NS": "Construction",
    "KPITTECH.NS": "Information Technology",
    "KSB.NS": "Capital Goods",
    "KAJARIACER.NS": "Consumer Durables",
    "KPIL.NS": "Construction",
    "KALYANKJIL.NS": "Consumer Durables",
    "KANSAINER.NS": "Consumer Durables",
    "KARURVYSYA.NS": "Financial Services",
    "KAYNES.NS": "Capital Goods",
    "KEC.NS": "Construction",
    "KFINTECH.NS": "Financial Services",
    "KIRLOSBROS.NS": "Capital Goods",
    "KIRLOSENG.NS": "Capital Goods",
    "KOTAKBANK.NS": "Financial Services",
    "KIMS.NS": "Healthcare",
    "LTF.NS": "Financial Services",
    "LTTS.NS": "Information Technology",
    "LICHSGFIN.NS": "Financial Services",
    "LTIM.NS": "Information Technology",
    "LT.NS": "Construction",
    "LATENTVIEW.NS": "Information Technology",
    "LAURUSLABS.NS": "Healthcare",
    "LEMONTREE.NS": "Consumer Services",
    "LICI.NS": "Financial Services",
    "LINDEINDIA.NS": "Chemicals",
    "LLOYDSME.NS": "Metals & Mining",
    "LUPIN.NS": "Healthcare",
    "MMTC.NS": "Services",
    "MRF.NS": "Automobile and Auto Components",
    "LODHA.NS": "Realty",
    "MGL.NS": "Oil Gas & Consumable Fuels",
    "MAHSEAMLES.NS": "Capital Goods",
    "M&MFIN.NS": "Financial Services",
    "M&M.NS": "Automobile and Auto Components",
    "MAHLIFE.NS": "Realty",
    "MANAPPURAM.NS": "Financial Services",
    "MRPL.NS": "Oil Gas & Consumable Fuels",
    "MANKIND.NS": "Healthcare",
    "MARICO.NS": "Fast Moving Consumer Goods",
    "MARUTI.NS": "Automobile and Auto Components",
    "MASTEK.NS": "Information Technology",
    "MFSL.NS": "Financial Services",
    "MAXHEALTH.NS": "Healthcare",
    "MAZDOCK.NS": "Capital Goods",
    "METROBRAND.NS": "Consumer Durables",
    "METROPOLIS.NS": "Healthcare",
    "MINDACORP.NS": "Automobile and Auto Components",
    "MSUMI.NS": "Automobile and Auto Components",
    "MOTILALOFS.NS": "Financial Services",
    "MPHASIS.NS": "Information Technology",
    "MCX.NS": "Financial Services",
    "MUTHOOTFIN.NS": "Financial Services",
    "NATCOPHARM.NS": "Healthcare",
    "NBCC.NS": "Construction",
    "NCC.NS": "Construction",
    "NHPC.NS": "Power",
    "NLCINDIA.NS": "Power",
    "NMDC.NS": "Metals & Mining",
    "NSLNISP.NS": "Metals & Mining",
    "NTPC.NS": "Power",
    "NH.NS": "Healthcare",
    "NATIONALUM.NS": "Metals & Mining",
    "NAVINFLUOR.NS": "Chemicals",
    "NESTLEIND.NS": "Fast Moving Consumer Goods",
    "NETWEB.NS": "Information Technology",
    "NETWORK18.NS": "Media Entertainment & Publication",
    "NEWGEN.NS": "Information Technology",
    "NAM-INDIA.NS": "Financial Services",
    "NUVAMA.NS": "Financial Services",
    "NUVOCO.NS": "Construction Materials",
    "OBEROIRLTY.NS": "Realty",
    "ONGC.NS": "Oil Gas & Consumable Fuels",
    "OIL.NS": "Oil Gas & Consumable Fuels",
    "OLECTRA.NS": "Automobile and Auto Components",
    "PAYTM.NS": "Financial Services",
    "OFSS.NS": "Information Technology",
    "POLICYBZR.NS": "Financial Services",
    "PCBL.NS": "Chemicals",
    "PIIND.NS": "Chemicals",
    "PNBHOUSING.NS": "Financial Services",
    "PNCINFRA.NS": "Construction",
    "PTCIL.NS": "Capital Goods",
    "PVRINOX.NS": "Media Entertainment & Publication",
    "PAGEIND.NS": "Textiles",
    "PATANJALI.NS": "Fast Moving Consumer Goods",
    "PERSISTENT.NS": "Information Technology",
    "PETRONET.NS": "Oil Gas & Consumable Fuels",
    "PFIZER.NS": "Healthcare",
    "PHOENIXLTD.NS": "Realty",
    "PIDILITIND.NS": "Chemicals",
    "PEL.NS": "Financial Services",
    "PPLPHARMA.NS": "Healthcare",
    "POLYMED.NS": "Healthcare",
    "POLYCAB.NS": "Capital Goods",
    "POONAWALLA.NS": "Financial Services",
    "PFC.NS": "Financial Services",
    "POWERGRID.NS": "Power",
    "PRAJIND.NS": "Capital Goods",
    "PRESTIGE.NS": "Realty",
    "PGHH.NS": "Fast Moving Consumer Goods",
    "PNB.NS": "Financial Services",
    "QUESS.NS": "Services",
    "RRKABEL.NS": "Capital Goods",
    "RBLBANK.NS": "Financial Services",
    "RECLTD.NS": "Financial Services",
    "RHIM.NS": "Capital Goods",
    "RITES.NS": "Construction",
    "RADICO.NS": "Fast Moving Consumer Goods",
    "RVNL.NS": "Construction",
    "RAILTEL.NS": "Telecommunication",
    "RAINBOW.NS": "Healthcare",
    "RAJESHEXPO.NS": "Consumer Durables",
    "RKFORGE.NS": "Automobile and Auto Components",
    "RCF.NS": "Chemicals",
    "RATNAMANI.NS": "Capital Goods",
    "RTNINDIA.NS": "Consumer Services",
    "RAYMOND.NS": "Realty",
    "REDINGTON.NS": "Services",
    "RELIANCE.NS": "Oil Gas & Consumable Fuels",
    "ROUTE.NS": "Telecommunication",
    "SBFC.NS": "Financial Services",
    "SBICARD.NS": "Financial Services",
    "SBILIFE.NS": "Financial Services",
    "SJVN.NS": "Power",
    "SKFINDIA.NS": "Capital Goods",
    "SRF.NS": "Chemicals",
    "SAMMAANCAP.NS": "Financial Services",
    "MOTHERSON.NS": "Automobile and Auto Components",
    "SANOFI.NS": "Healthcare",
    "SAPPHIRE.NS": "Consumer Services",
    "SAREGAMA.NS": "Media Entertainment & Publication",
    "SCHAEFFLER.NS": "Automobile and Auto Components",
    "SCHNEIDER.NS": "Capital Goods",
    "SCI.NS": "Services",
    "SHREECEM.NS": "Construction Materials",
    "RENUKA.NS": "Fast Moving Consumer Goods",
    "SHRIRAMFIN.NS": "Financial Services",
    "SHYAMMETL.NS": "Capital Goods",
    "SIEMENS.NS": "Capital Goods",
    "SIGNATURE.NS": "Realty",
    "SOBHA.NS": "Realty",
    "SOLARINDS.NS": "Chemicals",
    "SONACOMS.NS": "Automobile and Auto Components",
    "SONATSOFTW.NS": "Information Technology",
    "STARHEALTH.NS": "Financial Services",
    "SBIN.NS": "Financial Services",
    "SAIL.NS": "Metals & Mining",
    "SWSOLAR.NS": "Construction",
    "SUMICHEM.NS": "Chemicals",
    "SPARC.NS": "Healthcare",
    "SUNPHARMA.NS": "Healthcare",
    "SUNTV.NS": "Media Entertainment & Publication",
    "SUNDARMFIN.NS": "Financial Services",
    "SUNDRMFAST.NS": "Automobile and Auto Components",
    "SUPREMEIND.NS": "Capital Goods",
    "SUVENPHAR.NS": "Healthcare",
    "SUZLON.NS": "Capital Goods",
    "SWANENERGY.NS": "Diversified",
    "SYNGENE.NS": "Healthcare",
    "SYRMA.NS": "Capital Goods",
    "TBOTEK.NS": "Consumer Services",
    "TVSMOTOR.NS": "Automobile and Auto Components",
    "TVSSCS.NS": "Services",
    "TANLA.NS": "Information Technology",
    "TATACHEM.NS": "Chemicals",
    "TATACOMM.NS": "Telecommunication",
    "TCS.NS": "Information Technology",
    "TATACONSUM.NS": "Fast Moving Consumer Goods",
    "TATAELXSI.NS": "Information Technology",
    "TATAINVEST.NS": "Financial Services",
    "TATAMOTORS.NS": "Automobile and Auto Components",
    "TATAPOWER.NS": "Power",
    "TATASTEEL.NS": "Metals & Mining",
    "TATATECH.NS": "Information Technology",
    "TTML.NS": "Telecommunication",
    "TECHM.NS": "Information Technology",
    "TECHNOE.NS": "Construction",
    "TEJASNET.NS": "Telecommunication",
    "NIACL.NS": "Financial Services",
    "RAMCOCEM.NS": "Construction Materials",
    "THERMAX.NS": "Capital Goods",
    "TIMKEN.NS": "Capital Goods",
    "TITAGARH.NS": "Capital Goods",
    "TITAN.NS": "Consumer Durables",
    "TORNTPHARM.NS": "Healthcare",
    "TORNTPOWER.NS": "Power",
    "TRENT.NS": "Consumer Services",
    "TRIDENT.NS": "Textiles",
    "TRIVENI.NS": "Fast Moving Consumer Goods",
    "TRITURBINE.NS": "Capital Goods",
    "TIINDIA.NS": "Automobile and Auto Components",
    "UCOBANK.NS": "Financial Services",
    "UNOMINDA.NS": "Automobile and Auto Components",
    "UPL.NS": "Chemicals",
    "UTIAMC.NS": "Financial Services",
    "UJJIVANSFB.NS": "Financial Services",
    "ULTRACEMCO.NS": "Construction Materials",
    "UNIONBANK.NS": "Financial Services",
    "UBL.NS": "Fast Moving Consumer Goods",
    "UNITDSPR.NS": "Fast Moving Consumer Goods",
    "USHAMART.NS": "Capital Goods",
    "VGUARD.NS": "Consumer Durables",
    "VIPIND.NS": "Consumer Durables",
    "DBREALTY.NS": "Realty",
    "VTL.NS": "Textiles",
    "VARROC.NS": "Automobile and Auto Components",
    "VBL.NS": "Fast Moving Consumer Goods",
    "MANYAVAR.NS": "Consumer Services",
    "VEDL.NS": "Metals & Mining",
    "VIJAYA.NS": "Healthcare",
    "VINATIORGA.NS": "Chemicals",
    "IDEA.NS": "Telecommunication",
    "VOLTAS.NS": "Consumer Durables",
    "WELCORP.NS": "Capital Goods",
    "WELSPUNLIV.NS": "Textiles",
    "WESTLIFE.NS": "Consumer Services",
    "WHIRLPOOL.NS": "Consumer Durables",
    "WIPRO.NS": "Information Technology",
    "YESBANK.NS": "Financial Services",
    "ZFCVINDIA.NS": "Automobile and Auto Components",
    "ZEEL.NS": "Media Entertainment & Publication",
    "ZENSARTECH.NS": "Information Technology",
    "ZOMATO.NS": "Consumer Services",
    "ZYDUSLIFE.NS": "Healthcare",
    "ECLERX.NS": "Services"
}

# Ordered list of all NIFTY 500 tickers for ingestion
TICKER_LIST = sorted(list(TICKER_MAP.keys()))

# Dictionary mapping raw Yahoo symbols back to company keywords for NLP
# (We strip .NS for the NLP keyword matching)
TICKER_KEYWORDS = {}
for ticker in TICKER_MAP:
    clean_sym = ticker.replace('.NS', '')
    # E.g. RELIANCE.NS -> ['reliance', 'reliance.ns']
    TICKER_KEYWORDS[clean_sym] = [clean_sym.lower()]

# For some major companies, add more common aliases
COMMON_ALIASES = {
    'RELIANCE': ['reliance', 'ril', 'mukesh ambani'],
    'TCS': ['tcs', 'tata consultancy'],
    'HDFCBANK': ['hdfc bank', 'hdfcbank'],
    'INFY': ['infosys', 'infy'],
    'ICICIBANK': ['icici bank', 'icicibank'],
    'HINDUNILVR': ['hindustan unilever', 'hul'],
    'ITC': ['itc limited', 'itc '],
    'SBIN': ['sbi', 'state bank of india', 'sbin'],
    'BHARTIARTL': ['bharti airtel', 'airtel'],
    'TATAMOTORS': ['tata motors'],
    'BAJFINANCE': ['bajaj finance'],
    'WIPRO': ['wipro'],
    'LT': ['larsen', 'l&t '],
}

for ticker, aliases in COMMON_ALIASES.items():
    if ticker in TICKER_KEYWORDS:
        TICKER_KEYWORDS[ticker].extend(aliases)

# Provide a plain list of symbols (e.g. ['RELIANCE', 'TCS', ...])
TICKER_SYMBOLS = list(TICKER_KEYWORDS.keys())
